### ISSUE TITLE
Aplication loads properly but no data is shown in the screen

### ISSUE THREAD

**Issue by fidelram** [chanzuckerberg/cellxgene#440] opened 2018-11-15 09:13 UTC
I have two installations of cellxgene. One works properly and the other loads the data and starts the server but does not show it. All layout elements are loaded properly but no dots, histograms, etc are shown.

I tried to add the verbose argument but I do not get any error or warning message. 

Do you know how to debug this?

**Comment by bkmartinjr** [comment] 2018-11-15 14:20
Hi @fidelram - happy to help.  Could you provide additional information:
* are there any other messages in the Python console or Browser console (command-shift-I if using Chrome)
* describe the host configuration:
    * platform and browser version
    * is the browser and Python program running on the same host/VM?
    * output of `pip freeze`
* command line you used to launch the Python program
* can you describe how to reproduce the issue

Most typically these CORS errors are preceded by another issue.

**Comment by fidelram** [comment] 2018-11-15 15:31
Thanks for the response. 

The server and the client are located in different machines on an intranet.

I managed to get around the problem by replacing the `host="0.0.0.0"` by the actual ip address of the machine in `server/cli/launch.py`

Maybe you could add `--host` as an argument to `launch.py` (assuming that my solution is the correct one).

**Comment by bkmartinjr** [comment] 2018-11-15 15:37
There is an option present, `--listen-all`, which should do what you want.  Can you give that a try and see if it works for your use case?

**Comment by fidelram** [comment] 2018-11-15 15:54
Using that option I was able to reach the site from the external client. But except for the layout I didn't get any content. 

Looking at the html source code I can see that the http://0.0.0.0:port/ is used: `window.CELLXGENE.API={prefix:"http://0.0.0.0:8889/api/",version:"v0.2/"}`. From the external client I can not reach `0.0.0.0` and hence not data is loaded.

**Comment by fidelram** [comment] 2018-11-19 13:47
Here is what I am using:

# remote machine
cellxgene launch -v --listen-all -d -p 8889 --title test adata.h5ad

# client
http://(remote machine IP):8889/

**Comment by csweaver** [comment] 2018-11-29 00:03
I've replicated the issue, I'm working on a fix now!

**Comment by csweaver** [comment] 2018-12-05 22:53
Hi @fidelram The latest release should solve your issue. We have taken out the `--listen-all` option and replaced it with a `--host <host ip address>` option instead. 

Your full command should be `cellxgene launch -v --host <host ip address> -d -p 8889 --title test adata.h5ad`

**Comment by neuromusic** [comment] 2018-12-15 00:52
Closing since this issue appears to be fixed. 

Feel free to re-open @fidelram if you continue to experience the problem.

**Closed by neuromusic** 2018-12-15 00:52 UTC
Labels: backend, bug
