### ISSUE TITLE
JSON encoding of floats for expression data is super verbose 

### ISSUE THREAD

**Issue by csweaver** [chanzuckerberg/cellxgene#308] opened 2018-10-11 00:11 UTC
Need to use repr for float32 -- json module only lets us use predefined types so it will always be `float` pandas just rounds to number of decimal places instead of sigfig. Maybe look at simplejson or even writing our own?

**Comment by csweaver** [comment] 2018-11-12 23:35
@bkmartinjr I think you fixed this when you moved to using `to_records` for jsonification. Can we close this?

**Comment by bkmartinjr** [comment] 2018-11-13 02:39
Lets close it.  I don't think it is fixed, but it is a duplicate of #271

**Closed by bkmartinjr** 2018-11-13 02:39 UTC
Labels: backend, enhancement
