### ISSUE TITLE
Allow user to select number of differentially expressed genes

### ISSUE THREAD

**Issue by alokito** [chanzuckerberg/cellxgene#1003] opened 2019-11-01 19:59 UTC
Currently the differential analysis is limited to the top 10 genes. It would be nice if the user could input a number for the max number of genes they would like to select.

**Comment by colinmegill** [comment] 2019-11-01 20:08
Related to https://github.com/chanzuckerberg/cellxgene/issues/994

**Comment by alokito** [comment] 2019-11-01 20:11
Related to #95

**Comment by bkmartinjr** [comment] 2020-07-17 17:16
Closing as duplicate of #681.

**Closed by bkmartinjr** 2020-07-17 17:16 UTC
