### ISSUE TITLE
--experimental-annotations-ontology is throwing an error

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/cellxgene#2034] opened 2021-02-03 00:58 UTC
--experimental-annotations-ontology is throwing the error on v0.16.6: Error: Unable to load ontology terms; Syntax error loading OBO ontology

Angela reported in #cellxgene-users

Steps to reproduce: 
`(venv) schambers@CZIMACOS3069 cellxgenedev % make start-server CXG_OPTIONS="--experimental-annotations-ontology --experimental-enable-reembedding --debug" DATASET=./data/krasnow_lab_human_lung_cell_atlas_smartseq2-2-remixed.h5ad
cellxgene launch -p 5005 --experimental-annotations-ontology --experimental-enable-reembedding --debug ./data/krasnow_lab_human_lung_cell_atlas_smartseq2-2-remixed.h5ad
[cellxgene] Starting the CLI...
[cellxgene] in debug mode, setting verbose=True and open_browser=False
[cellxgene] Loading data from krasnow_lab_human_lung_cell_atlas_smartseq2-2-remixed.h5ad, this may take a while...
Error: Unable to load ontology terms
Syntax error loading OBO ontology
make: *** [start-server] Error 1
(venv) schambers@CZIMACOS3069 cellxgenedev % `

**Comment by bkmartinjr** [comment] 2021-02-05 00:05
This was caused by a malformed term definition in the default ontology, rather than a bug in cellxgene.   By default, cellxgene loads the Cell Ontology from the permalink:  http://purl.obolibrary.org/obo/cl.obo

The latest OBO file at this URL contains a term that has a typo.  The cellxgene error handling rejects the entire ontology when any malformed text is in the OBO.   As a work-around, you can download the latest cell ontology OBO, fix the error, and specify the corrected OBO on the command line, eg, 

`cellxgene launch mydata.h5ad --experimental-annotations-ontology  --experimental-annotations-ontology-obo corrected.cl.obo`

The malformed term is below.  See the xref, which should read `xref: xref:(ILX\:0770149)`  (missing colon after second xref, and missing escape after ILX).

```
[Term]
id: CL:4023011
name: Lamp5 GABAergic cortical interneuron
def: "A GABAergic neuron located in the cerebral cortex that expresses Lamp5" [PMID:30382198]
xref: xref (ILX:0770149)
is_a: CL:0010011 ! cerebral cortex GABAergic interneuron
intersection_of: CL:0000099 ! interneuron
intersection_of: capable_of GO:0061534 ! gamma-aminobutyric acid secretion, neurotransmission
intersection_of: RO:0002100 UBERON:0000956 ! has soma location cerebral cortex
intersection_of: RO:0002292 https://identifiers.org/ensembl:ENSMUSG00000027270 ! expresses Lamp5
relationship: RO:0002292 https://identifiers.org/ensembl:ENSMUSG00000027270 ! expresses Lamp5
created_by: http://orcid.org/0000-0001-7258-9596
```

We can certainly improve our error handling, to make the failure more more obvious.  We can possible add support to ignore the malformed terms.  I'll look into both before closing this issue.

CC: @aopisco

**Comment by bkmartinjr** [comment] 2021-02-05 17:31
Our current OBO parsing library has no easy way to recover from an error by ignoring a term and continuing.  Linked PR improves the error message, to make it clear what failed.

**Comment by bkmartinjr** [comment] 2021-02-05 19:09
Link: obophenotype/cell-ontology#930

**Closed** 2021-02-05 20:19 UTC
Labels: P1, bug
