### ISSUE TITLE
Review and confirm repo docs

### ISSUE THREAD

**Issue by fionagriffin** [chanzuckerberg/cellxgene#232] opened 2018-09-17 20:53 UTC
- [x] Review and confirm repo docs:
    - [x] Readme
    - [x] Install / getting started
    - [x] Contact / issue / help information
    - [x] License
    - [x] Contribution guidelines
    - [x] Clean, reviewed & validated REST API documentation and Swagger spec

**Comment by bkmartinjr** [comment] 2018-11-14 00:59
duplicate of #131?

**Comment by fionagriffin** [comment] 2018-11-14 18:06
The only difference I see from #131 is "Clean, reviewed & validated REST API documentation and Swagger spec". @csweaver do we want to change this issue?

**Closed** 2018-11-27 22:44 UTC
Labels: Priority 3
