### ISSUE TITLE
Change color scheme

### ISSUE THREAD

**Issue by joshua-gould** [chanzuckerberg/cellxgene#726] opened 2019-04-22 20:01 UTC
I would like the option to change the color assigned to a categorical value and the color scheme used for continuous variables.

**Comment by csweaver** [comment] 2019-04-24 17:01
Thanks for the suggestion. Possible duplicate of #446. We are thinking about adding this at some point.

Would you want to specify colors on launch or make a selection in the app?

**Comment by joshua-gould** [comment] 2019-04-24 19:38
The ability to change colors is more important, but both are useful.

**Comment by bkmartinjr** [comment] 2019-04-24 20:01
Hi @joshua-gould - if you don't mind, could you expand on how you ?  Specifically:
* how would you use this feature in your analysis workflow?
* what problem does it solve for you?

We have some other requests for similar functionality, and we want ensure we understand the problem this solves for you.    For example, is this a matter of aesthetics, are you using this to create images for presentations, is it an accessibility issue, or?  

Thank you!

**Comment by joshua-gould** [comment] 2019-04-24 20:20
My main use case is for interactive exploration of the data. In that case, I want to be able to change the color scheme range for continuous values and change the color of categorical values to visually merge/separate clusters.

**Comment by colinmegill** [comment] 2019-04-24 20:44
@joshua-gould changing the range may be handled by #672, could you confirm?

**Comment by joshua-gould** [comment] 2019-04-24 20:45
Yes, it seems to be

**Comment by colinmegill** [comment] 2019-04-24 20:49
Thanks so much! I think the categorical case is covered by #446, and if there is no objection we might close this issue. Want to make sure we aren't missing anything.

**Comment by joshua-gould** [comment] 2019-04-24 20:49
Sounds good. Thanks.

**Closed** 2019-04-24 20:50 UTC
Labels: duplicate, enhancement
