### ISSUE TITLE
Document the gene threshold(s) that were used to narrow down an annotation selection

### ISSUE THREAD

**Issue by liaprins-czi** [chanzuckerberg/cellxgene#1353] opened 2020-04-06 18:13 UTC
Reported when working with Angela's group: users want a way to make annotations’ cell selections more easily reproduced, as per chenlingantelope@gmail.com. Chenling’s specific suggestion: Within annotations .CSV, document the gene threshold(s) that were used to narrow down the selection of cells per label.

**Why?**
- It would be a helpful starting point for their next pilots, to start with annotations based on the same genes used initially.
- It'd be useful to see if, for different datasets, they need to use different gene expression thresholds when creating annotations’ selections.
- For publishing, they’d like to include the gene expression levels, in addition to the genes themselves, used to determine their cell types.
- Chenling rarely uses lasso tool to make annotations’ selections: too imprecise, but uses gene gating.

**NOTE:** This suggestion seems to be only relevant when a user follows this gene gating method when creating a label annotation. If combined with lasso, or if they used lasso exclusively, it would no longer be useful (nor possible?) to retrieve this info.

**Comment by signechambers1** [comment] 2020-10-01 01:08
Very helpful context, closing as a duplicate of [997](https://github.com/chanzuckerberg/cellxgene/issues/997)

**Closed by signechambers1** 2020-10-01 01:08 UTC
Labels: user request
