### ISSUE TITLE
TM_Droplet name nan

### ISSUE THREAD

**Issue by colinmegill** [chanzuckerberg/cellxgene#409] opened 2018-11-05 20:28 UTC
This seems like an error worth a sanity check on the metadata parsing:

![image.png](https://images.zenhubusercontent.com/5588c9564f7a08fbb7f35803/4b8d9ccc-5e39-4fac-a3fb-f136ca844169)

**Comment by bkmartinjr** [comment] 2018-11-13 23:05
I'll fix this - I know the cause and resolution. It is a result of how pandas categorical dataframes handle unassigned values.

**Comment by bkmartinjr** [comment] 2018-11-16 19:23
duplicate of #410

**Closed by bkmartinjr** 2018-11-16 19:23 UTC
