### ISSUE TITLE
Selecting cells via Distribution histogram: improve user experience

### ISSUE THREAD

**Issue by grst** [chanzuckerberg/cellxgene#937] opened 2019-09-19 07:41 UTC
Being able to select cells via the gene expression histogram is a really cool and useful feature, that enables me to assess gene co-expression in different clusters:

![2019-09-19_09:37:34_947x371](https://user-images.githubusercontent.com/7051479/65223276-21ac6400-dac1-11e9-9669-458f288cfa48.png)

I just found it hard to figure out that this works in the first place. In fact, I wouldn't if it hadn't been shown to me. Therefore, it would be great if you could find a way to

- make it clear to users that don't have a lot of experience with cellxgene that you can select cells using the histogram and
- that you can select on multiple histograms simultaneously and
- that selection on multiple histograms means `condition1 AND condition2` rather than `OR`. 

Best, 
Gregor 

(This has been previously discussed this with @sidneymbell via email)

**Comment by signechambers1** [comment] 2020-09-30 23:07
Thank you @grst ! We definitely want to do more to help users discover and understand this functionality. I'm closing this as a duplicate of [this ticket](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell/59)

**Closed by signechambers1** 2020-09-30 23:07 UTC
