### ISSUE TITLE
Programmatic Control and Headless

### ISSUE THREAD

**Issue by hisplan** [chanzuckerberg/cellxgene#603] opened 2019-02-19 19:19 UTC
IGV provides a way to “programmatically” control the UI such as loading BAM file, go to a specific genomic locus, take a screenshot, and etc.

This feature is especially helpful if you want to apply the same steps to hundreds of different patient sample data.

IGV kinda came up with their own script language, but I think if one could use Python or JavaScript, this would be better - for example:

```python
from cellxgene import api

client = api.launch(headless=True, ...)
client.load('...')
...
client.take_screenshot(out='test.png')
```

Furthermore, if the UI can launch completely “headless”, this will allow one to run it in a massively parallel fashion in the cloud or HPC.

**Comment by neuromusic** [comment] 2019-02-19 19:43
Interesting proposal!

I'm curious what you're trying to do that you want to use cellxgene like this?

**Comment by csweaver** [comment] 2019-02-21 02:23
Hi @hisplan I think I have some notion of what you are trying to achieve. If you are interested in doing this now, without an API to cellxgene, there are several browser automation tools available that you can write your scripts in. I've been using [puppeteer](https://github.com/GoogleChrome/puppeteer) to run some UI tests, you can see an example in this PR [here](https://github.com/chanzuckerberg/cellxgene/pull/604). But [selenium](https://www.seleniumhq.org/) is another popular option. Both work in headless mode.

**Comment by hisplan** [comment] 2019-02-21 03:32
No rocket science. Just thought that it would be awesome if one can 
- easily share (not using deep links, but more like in Jupyter notebook fashion)
- fully automate and reproduce the results

If the code snippet above can be used in a notebook, one can even do something like below to embed the screenshot as part of the notebook…

```python
from IPython.display import Image
from IPython.core.display import HTML 

Image(url= "…/test.png")
```

I happened to have some UI automated testing experience using Selenium, protractor, phantom, … I do not want to inspect elements, wait some arbitrary time until something becomes active. Especially, I do not want to see the automation code break because of some element ID changes.

I’ll pass. I can still live without this feature :-) BTW, good to see that cellxgene is backed by e2e testing.

**Comment by signechambers1** [comment] 2020-09-29 02:09
Closing as a quasi - duplicate of https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/cellxgene/658

**Closed by signechambers1** 2020-09-29 02:09 UTC
