### ISSUE TITLE
compute tier

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#1545] opened 2020-06-04 18:49 UTC
Add support for a separate, optional, compute tier:
1. Improve scale & performance by moving compute tasks from web-tier to dedicated compute tier when available.
2. Explore various dispatching/serving options, such as: TileDB UDF, dedicated/own, etc.
3. Deploy for Corpora

**Comment by signechambers1** [comment] 2020-10-15 00:11
Closing as a duplicate of https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell/38

**Closed by signechambers1** 2020-10-15 00:11 UTC
