### ISSUE TITLE
tooltip layout clips

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#1622] opened 2020-07-13 15:13 UTC
the hover-over tooltip for a disabled color-by button clips as it displays "left"  -  it should render right.

![image.png](https://images.zenhubusercontent.com/5af38d3b4b5806bc2bd28ea9/2b3daefa-6ac9-434d-8175-5ddf909b5101)

**Comment by maniarathi** [comment] 2020-07-27 20:46
Duplicate of #1416, closing.

**Closed by maniarathi** 2020-07-27 20:46 UTC
Labels: bug
