### ISSUE TITLE
new view of genes identified by differential expression

### ISSUE THREAD

**Issue by neuromusic** [chanzuckerberg/cellxgene#528] opened 2018-12-21 23:43 UTC
From #460: 

> view [top differentially expressed genes] not in a scrollable list, but as a matrix or dotplot/heatmap

**Comment by signechambers1** [comment] 2020-09-29 01:50
Closing as a quasi - duplicate of https://github.com/chanzuckerberg/cellxgene/issues/632. Gene sets + heatmap will allow users to do this

**Closed by signechambers1** 2020-09-29 01:50 UTC
