### ISSUE TITLE
volcano gene plot

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#1544] opened 2020-06-04 18:47 UTC
1. Users can see volcano plot with all genes when diffexp button clicked
2. Users can make gene set with custom expression threshold from volcano plot interface

includes standalone volcano plot component

**Comment by colinmegill** [comment] 2020-06-04 18:55
See: https://github.com/chanzuckerberg/cellxgene/issues/994

**Comment by signechambers1** [comment] 2020-10-15 00:09
Closing as a duplicate of 994

**Closed by signechambers1** 2020-10-15 00:09 UTC
