### ISSUE TITLE
Use blueprint icon variables everywhere

### ISSUE THREAD

**Issue by colinmegill** [chanzuckerberg/cellxgene#2105] opened 2021-03-15 22:21 UTC
Tech debt issue: 

`icon={<Icon icon="trash" iconSize={10} />}`

becomes 

`icon={<Icon icon={IconName.TRASH} iconSize={10} />}`

**Comment by signechambers1** [comment] 2021-04-06 18:50
Closing as a duplicate of https://github.com/chanzuckerberg/cellxgene/issues/2120

**Closed by signechambers1** 2021-04-06 18:50 UTC
