### ISSUE TITLE
If only one cell is in view histograms collapse

### ISSUE THREAD

**Issue by seve** [chanzuckerberg/cellxgene#1593] opened 2020-06-26 18:05 UTC
![image](https://user-images.githubusercontent.com/8716829/85887582-eb60eb00-b79c-11ea-97ab-949fb28884c4.png)

https://cellxgene.dev.single-cell.czi.technology/d/pbmc3k.cxg/

**Comment by bkmartinjr** [comment] 2020-06-26 18:24
I think this is intentional, but assigning to Colin to consider.

**Comment by maniarathi** [comment] 2020-07-21 00:14
Hey @colinmegill , if this is on purpose, can you close this please with a note?

**Comment by maniarathi** [comment] 2020-07-27 20:43
Working as intended.

**Closed by maniarathi** 2020-07-27 20:43 UTC
Labels: bug
