### ISSUE TITLE
[BUG] max-category-items is not working

### ISSUE THREAD

**Issue by z5ouyang** [chanzuckerberg/cellxgene#2225] opened 2021-05-24 22:18 UTC
**Describe the bug**
Even after I launch with "--max-category-items", the category with more unique values is still showing. 
Thought it was fixed in #812, but it exists in v0.16.8

**To Reproduce**
1. ```cellxgene launch ... --max_category_items 100```
2. ```[cellxgene] Warning: Obs annotation 'barcode' has 17663 categories, this may be cumbersome or slow to display. We recommend setting the --max-category                                           -items option to 500, this will hide categorical annotations with more than 500 categories in the UI```

**Expected behavior**
The above warning should not appear and the category barcode should not be shown on the page (below).

**Screenshots**
![image](https://user-images.githubusercontent.com/30639029/119413822-3e8c3800-bca3-11eb-9a74-676cb1b7b574.png)

**Version (please complete the following information):**
 - Desktop or hosted?: hosted
 - Browser (if hosted) [e.g. chrome, safari]: chrome
 - Version [e.g. 0.13.0]: 0.16.8

**Additional context**

**Comment by MaximilianLombardo** [comment] 2021-05-25 20:08
Hey,

Thanks for this information.

A couple of clarifications - by hosted, do you mean that you have set up a self-hosted system or are you using the hosted explorer on the cellxgene data portal?

In the screenshot you posted, it appears that the "color by" icon next to barcode is not active, so perhaps the only bug is that the warning messages are being displayed improperly? The dataset where you got this bug isn't publicly available is it (i.e. so I can replicate)?

For the time being, since the barcode column seems to correspond to cellIDs that are also represented in the index of the `obs` dataframe, would a temporary solution be to remove that column from `obs` entirely or is there a specific reason that you have included it there?

**Comment by z5ouyang** [comment] 2021-05-25 21:00
Thanks for the reply. Host means we host the data internally, not from your data portal.

According to the [document](https://chanzuckerberg.github.io/cellxgene/posts/launch): "omits categorical metadata fields that contain more than N distinct values" means the barcode should not even be there, correct? And you are correct, it cannot be "color by". Sorry, the data is not public available. But I can create one with pbmc3k just using cell name, if you want me to.

For the time being, I can remove that column, but since our application is for user to deposit their h5ad, I was trying to use cellxgene function to limit the annotation with large numbers. If this option from cellxgene is not working, I will do work around.

Thank you!

**Comment by MaximilianLombardo** [comment] 2021-06-01 13:37
Hey @z5ouyang,

Thank you for the details! 

Yes, I agree - that wording implies that metadata fields with more than N unique values should not be displayed. No need to set up a dummy example, @maniarathi was able to reproduce. 

If you can manage with the workaround for the time being that would be great! We are looking at the issue, and figuring out how soon we can prioritize coming up with a fix for it. Let us know if you encounter any other issues that are not solved by the workaround!

**Comment by signechambers1** [comment] 2021-07-13 18:09
Closing due to https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/cellxgene/2296

**Closed** 2021-07-29 23:05 UTC
Labels: bug
