### ISSUE TITLE
[BUG] clipping and selection of genes is not possible with 0.16.7, but possible with 0.15.0

### ISSUE THREAD

**Issue by ilibarra** [chanzuckerberg/cellxgene#2093] opened 2021-03-05 15:07 UTC
**Describe the bug**
During a SCANPY course and in a toy dataset (PBMC), students have found that the selection of cells based based on gene expression and clipping in histograms (e.g. GAPDH) is not possible. For other properties this is able to be done (n_counts per cell, n_genes per cell). This is specifically ocurring in 0.16.7, and it is solved by installing 0.15.0

**To Reproduce**
1. Install cellxgene 0.16.7
2. Start a session with the PBMC dataset and select one gene in the histogram (GADPH)
3. Clip expression levels to select cells. Nothing is updated in the main embedding as this is done.
4. Close and install cellxgene 0.15.0
5. Repeat steps 2 and 3. Behavior fixed and cells are highlighted in the embedding.

**Expected behavior**
Cells should be selected by specific genes.

**Screenshots**

**Version (please complete the following information):**
 - Desktop
 - Chrome (I can confirm version if necessary)

Thank you,

**Comment by bkmartinjr** [comment] 2021-03-22 22:10
Hello @ilibarra -- I am unable to reproduce this issue using latest Chrome/Linux, cellxgene 0.16.7, Python 3.8 and a command:

> cellxgene launch https://cellxgene-example-data.czi.technology/pbmc3k.h5ad

When I do this, I can add genes and select them.  The main embedding updates as I do this.

Could you provide more information on your configuration:
* host OS
* chrome version
* python version
* modules installed (output of `pip list`)
* dataset

Thanks!

**Comment by bkmartinjr** [comment] 2021-03-24 14:53
assigning this to @signechambers1 until we get a test case.  Please feel free to reassign when we know how to reproduce.

**Comment by MaximilianLombardo** [comment] 2021-04-14 20:48
Hey @signechambers1 I was unable to reproduce this bug in cellxgene 0.16.7

I installed the version of cellxgene in a fresh conda environment running python 3.8 and viewed the application using google chrome Version 89.0.4389.114 (Official Build) (x86_64)

I launched cellxgene with the pbmc 3k dataset using the following command:

`cellxgene launch https://cellxgene-example-data.czi.technology/pbmc3k.h5ad`

**Comment by signechambers1** [comment] 2021-04-14 21:54
Thanks @MaximilianLombardo.

@ilibarra we aren't able to reproduce your problem so I'm going to close this issue. If you run into this again please let us know!

**Closed by signechambers1** 2021-04-14 21:54 UTC
Labels: P1, bug
