### ISSUE TITLE
List interesting gene sets (publication use case)

### ISSUE THREAD

**Issue by colinmegill** [chanzuckerberg/cellxgene#852] opened 2019-07-16 19:41 UTC
Allow adding a list of known interesting sets of genes - 10's, 100's of genes - in named sets. Good for quick 'show and tell' use cases where someone just wants to click through, after analysis work has been done and dataset is published.

**Comment by seve** [comment] 2019-07-16 20:07
This would also be a good addition for static deployments

**Comment by signechambers1** [comment] 2020-10-21 20:48
Closing as a duplicate of https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell/64

**Closed by signechambers1** 2020-10-21 20:48 UTC
Labels: P3
