### ISSUE TITLE
Add formalization / clarity to current selection state

### ISSUE THREAD

**Issue by colinmegill** [chanzuckerberg/cellxgene#652] opened 2019-03-19 19:06 UTC
Since users can take actions given current selection (create an annotation, subset to it etc), it would be great if it were reinforced as a concept in the ui

![image](https://user-images.githubusercontent.com/1770265/54633817-2c1c7100-4a3e-11e9-8ba3-00bd98142491.png)

Thanks to @happyimadesignr!

**Comment by bkmartinjr** [comment] 2019-05-14 19:24
duplicate of #559 ?

**Comment by colinmegill** [comment] 2019-05-14 19:40
Not quite! #559 is about a value, but we haven't implemented because it takes up too much horizontal space. I could see doing #559 in tooltip if you hover on the value - ie., if the value for `tissue > heart` is `10` and that is reflective of world, and you hover on `10`, it would tell you: `heart in current selection: 5`, `heart in universe: 500`

This issue is really about making 'current selection' a more prominent noun in the interface, to reinforce to users that they can take an action on it (ie., subset). The mock, above, is a reminder not necessarily a spec. 

Neither are urgent.

**Comment by colinmegill** [comment] 2019-07-11 17:32
This is also an opportunity to copy current cell selection to clipboard/csv, that further reinforces that it's a list of cell ids.

**Comment by signechambers1** [comment] 2020-12-23 17:31
Closing as a low priority for 2021

**Closed by signechambers1** 2020-12-23 17:31 UTC
