### ISSUE TITLE
Add backoff on failed requests

### ISSUE THREAD

**Issue by mckinsel** [chanzuckerberg/cellxgene#1985] opened 2020-11-19 12:54 UTC
Currently we retry failed requests to the backend forever at a fixed period. This is not helpful when the backed is having a transient issue.

Instead, we should have a fixed number of retries with a little jitter and exponential backoff.

**Comment by maniarathi** [comment] 2020-11-19 16:54
Closing this one as a duplicate of #1981. Timmy beat you to it just slightly :) but thank you for creating this!!

**Closed by maniarathi** 2020-11-19 16:54 UTC
Labels: bug
