### ISSUE TITLE
Zooming is not right when cellxgene launches

### ISSUE THREAD

**Issue by cakirb** [chanzuckerberg/cellxgene#784] opened 2019-05-23 14:09 UTC
In some datasets that we are testing, we noticed that the plot view does not show the all cells when cellxgene launches. We can only see the other cells after zooming out.

When the page opens and after zooming out:
![Picture1](https://user-images.githubusercontent.com/39408202/58258506-c6fd3880-7d6a-11e9-96ec-cf26e651989a.png)
![Picture2](https://user-images.githubusercontent.com/39408202/58258461-b056e180-7d6a-11e9-874d-3043aaefb73a.png)

Due to being under-development study, I cannot share the dataset; but I can send obsm.csv that you can find below, hope it helps: [dataset_obsm.txt](https://github.com/chanzuckerberg/cellxgene/files/3212499/dataset_obsm.txt)

**Comment by bkmartinjr** [comment] 2019-05-23 15:23
@cakirb, thanks for the bug report.   This is likely a duplicate of #655, which was just fixed, and will be released in an upcoming release.   I will leave this issue open we have confirmed that it is resolved with your original data.

**Comment by bkmartinjr** [comment] 2019-05-30 00:24
@cakirb - we just release 0.10.0 which I believe fixes this issue.   When you get a chance, would you do me the favor of testing with your data set, and letting me know how it goes?  Thanks!

**Comment by cakirb** [comment] 2019-05-30 08:54
Hi @bkmartinjr, I have checked those datasets with the new release 0.10.0. Zooming is much better now, but in some datasets (like below) there are a few cells which are very close or not seen at the top and bottom edges, they can be seen by a little zooming out. And the plot was not centered exactly. Other than that, everything seems OK.

![image](https://user-images.githubusercontent.com/39408202/58620296-a4b17080-82be-11e9-8848-549ea69ab580.png)

**Comment by bkmartinjr** [comment] 2019-05-30 13:27
Hi @cakirb - I have reproduced this.  The dots are (literally) on the border with our new scaling.  I need to add a gutter around the canvas.  Will leave this issue open while I resolve it.  Thanks!!!

**Closed** 2019-05-30 20:31 UTC
Labels: bug, frontend

**Comment by bkmartinjr** [comment] 2019-05-30 20:57
@cakirb - this should now be resolved.  Please open if you find otherwise.  Thanks for the bug report!

**Comment by cakirb** [comment] 2019-05-31 08:18
Hi @bkmartinjr, yes it seems very good now. Thanks for fixing!!
