### ISSUE TITLE
Won't subset until clear DE (after following certain actions first...)

### ISSUE THREAD

**Issue by liaprins-czi** [chanzuckerberg/cellxgene#1437] opened 2020-04-29 17:50 UTC
To reproduce (I am pretty sure it is this full sequence of events, I have tried refreshing and starting at step 2 but it doesn't happen for me then):
1. Run DE 
2. Subset to some cells
3. Undo subset
4. Run another DE
5. Select some cells to subset (can do either lass or category or continuous selection; all reproduced this bug for me): when try to subset, the button doesn't work

![won't subset until clear DE](https://user-images.githubusercontent.com/53277128/80627873-67d98680-8a05-11ea-8ca0-fc16950acec0.gif)

Here is the console:

![Screen Shot 2020-04-29 at 10 25 41 AM](https://user-images.githubusercontent.com/53277128/80629045-22b65400-8a07-11ea-8ffc-5e3ff25d1114.png)

**Comment by bkmartinjr** [comment] 2020-05-20 16:57
This is very likely a duplicate of #1486

**Comment by bkmartinjr** [comment] 2020-07-17 03:25
Fixed by #1571

**Closed by bkmartinjr** 2020-07-17 03:25 UTC
Labels: bug
