### ISSUE TITLE
More differential expressed genes

### ISSUE THREAD

**Issue by GiacomoMa** [chanzuckerberg/cellxgene#1572] opened 2020-06-17 10:19 UTC
Dear cellxgene,

Would it be possible to retrieve a list of 100 differentially expressed genes, instead of top 10? They would not be necessarily displayed, but maybe as .csv file.

Many thanks for the attention.
Best,
Giacomo

**Comment by colinmegill** [comment] 2020-06-17 16:02
Hi @GiacomoMa! Yes, this is under development. You can follow #1539 and #994, as those issue are closed, the numbers of genes returned will be variable and under your control.

**Comment by bkmartinjr** [comment] 2020-07-17 17:16
Closing as duplicate of #681.

**Closed by bkmartinjr** 2020-07-17 17:16 UTC
