### ISSUE TITLE
Save or download point of data analysis

### ISSUE THREAD

**Issue by renesit** [chanzuckerberg/cellxgene#461] opened 2018-11-19 21:24 UTC
Would love to be able to save or download data analysis at a given stop point. Would not use cellxgene if I have to recompute everything on my computer. It would be a waste of time to do double the analysis. Thanks!

**Comment by GenevieveHaliburton** [comment] 2018-11-27 21:20
Hi @renesit thanks for your suggestion! A few follow up questions for you: What do you mean when you say "data analysis"? Do you mean the processed file after you run `cellxgene prepare` (which contains the computed clusters and the results for projection in tsne space)? Or do you mean you'd like to download something else (i.e. an image of a tsne projection, or a list of differentially expressed genes, or cell IDs from a certain selected cluster, etc)? Any specific types of analyses/results you'd like to see would be really helpful. Thanks!

**Comment by colinmegill** [comment] 2018-12-06 21:38
@renesit if I remember correctly from our conversation, you were wondering about the 'state' you are able to create in the application. The challenge is, if you've already made subsets and selections, then recreating those manually if you want to take a 'next step' which cellxgene can't accomplish. Does that capture your concern or miss it?

**Comment by bkmartinjr** [comment] 2018-12-06 23:03
Can you add some thoughts as to how this selection state would be saved?    What would be useful?   For example:
* save the selected list of cells (obs indices in ScanPy) as a CSV file?
* add a new annotation to each obs/cell that is selected and save the modified H5AD file?
Or?

**Comment by renesit** [comment] 2018-12-06 23:18
Hi @GenevieveHaliburton and @bkmartinjr, if possible I would actually like to be able to download all of which you mentioned. 
Cluster computed: so that I can easily re-integrate it back into my R or Python notebook. As a H5AD file would be amazing. 
Images, and list of DE genes: so I can use them for a presentation/poster or run them on IPA to look at pathways. The file can be a pdf for images and csv file for DE genes

**Comment by GenevieveHaliburton** [comment] 2018-12-18 22:52
Thanks @renesit!

> Cluster computed: so that I can easily re-integrate it back into my R or Python notebook. As a H5AD file would be amazing.

This should be available now, if I understand your comment correctly! Clustering and dimensionality reduction is performed prior to `cellxgene launch`,  in `cellxgene prepare`, so you can use the output of `cellxgene prepare`  h5ad file in your own notebooks. For example, if I started with expression matrix file `my_matrix.loom`, I could run `cellxgene prepare my_matrix.loom --output=prepared_matrix.h5ad` to perform dimensionality reduction and compute clusters (it just runs scanpy under the hood). The output file `prepared_matrix.h5ad` has an entry for UMAP and TSNE projections, and louvain cluster assignment.

> Images, and list of DE genes: so I can use them for a presentation/poster or run them on IPA to look at pathways. The file can be a pdf for images and csv file for DE genes

Great suggestion! We'll think about how to incorporate this.

**Comment by zhangguy** [comment] 2019-09-18 18:22
It'll be very helpful if we could save the lasso selected cell indices, either write back to the h5ad or download as a file. Seems that we couldn't do it now.

**Comment by bkmartinjr** [comment] 2019-09-18 19:50
@zhangguy - this will be easily done with the upcoming cell labelling feature (aka manual annotations).   This will land in our next release as an experimental/alpha feature.   See #837 for an early look.

**Comment by signechambers1** [comment] 2020-09-29 01:07
Closing as a duplicate of [#658 Saving browser state](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/cellxgene/658) and [#15 exporting gene sets] (https://github.com/chanzuckerberg/single-cell/issues/15)

**Closed by signechambers1** 2020-09-29 01:07 UTC
