### ISSUE TITLE
Gene names not loading

### ISSUE THREAD

**Issue by ambrosejcarr** [chanzuckerberg/cellxgene#874] opened 2019-08-07 21:16 UTC
I have a small h5ad file that looks as follows: 

```python
In [11]: test = anndata.read_h5ad("merfish.h5ad")                                                                                              

In [12]: test                                                                                                                                  
Out[12]: 
AnnData object with n_obs × n_vars = 422 × 140 
    obs: 'region_id', 'x_region', 'y_region'
    var: 'gene_name'
    uns: 'assay', 'authors', 'notes', 'organism', 'sample_type', 'year'
    obsm: 'X_spatial'

In [13]: test.var_names                                                                                                                        
Out[13]: 
Index(['ABCA2', 'AFAP1', 'AFF4', 'AGPS', 'AKAP11', 'ALMS1', 'ALPK2', 'AMOTL1',
       'ANKRD52', 'ARL10',
       ...
       'blank001', 'blank002', 'blank003', 'blank004', 'blank005',
       'notarget001', 'notarget002', 'notarget003', 'notarget004',
       'notarget005'],
      dtype='object', name='index', length=140)
```

When I attempt to load this into `cellxgene`, the genes do not appear to load properly. Both the following yield the same view: 

```bash
$ cellxgene launch ~/projects/chanzuckerberg/spatial-warehouse/merfish.h5ad --var-names=gene_name
```
```bash
$ cellxgene launch ~/projects/chanzuckerberg/spatial-warehouse/merfish.h5ad
```

![image](https://user-images.githubusercontent.com/5239152/62658449-d7b75680-b936-11e9-898e-10494694c3ba.png)

Data file is attached here for reference. 

[data.zip](https://github.com/chanzuckerberg/cellxgene/files/3478936/data.zip)

**Comment by bkmartinjr** [comment] 2019-09-11 20:34
@ambrosejcarr - I am unable to reproduce.   When I run with the supplied file, gene names show up fine (by default, no special CLI params needed).   Can you provide more details on how to reproduce the issue you are seeing?

![image.png](https://images.zenhubusercontent.com/5af38d3b4b5806bc2bd28ea9/0998cfca-bf2b-48f4-860e-2dcd2e972b2f)

and

![image.png](https://images.zenhubusercontent.com/5af38d3b4b5806bc2bd28ea9/849d5a91-fa58-4ea7-9f35-950c826f5c24)

**Comment by bkmartinjr** [comment] 2019-09-11 20:36
one additional thought - you may be tripped up by the UI bug where our gene autosuggest text box says "No matching genes" when you first give it keyboard focus.

This is bug #865, and is slated for fix in 0.12.   But it is a component feedback error, rather than a problem loading gene names.

**Comment by bkmartinjr** [comment] 2019-09-16 16:18
Have discussed with @ambrosejcarr and he was indeed misled by the UI gotcha noted in the previous comment. 

Duplicate of #865

**Comment by bkmartinjr** [comment] 2019-09-16 16:18
closing as dup

**Closed by bkmartinjr** 2019-09-16 16:18 UTC
Labels: bug
