### ISSUE TITLE
Gene sets - persistent

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#1539] opened 2020-06-04 18:21 UTC
A user's gene sets are persistent across sessions, for all deployment platforms (hosted and desktop)

**Comment by signechambers1** [comment] 2020-10-15 00:39
Closing as a duplicate of https://github.com/chanzuckerberg/single-cell/issues/15

**Closed by signechambers1** 2020-10-15 00:39 UTC
