### ISSUE TITLE
move position of color bar

### ISSUE THREAD

**Issue by aopisco** [chanzuckerberg/cellxgene#1174] opened 2020-02-25 00:38 UTC
it would be great if we could move the scale bar when coloring by gene. sometimes it sits exactly on the top of the population of interest which makes it hard to see

**Comment by bkmartinjr** [comment] 2020-02-25 00:54
assign to Lia to propose a refinement

**Comment by liaprins-czi** [comment] 2020-02-25 16:51
Great news, I have already designed this. It is part of a redesign/reformatting of the gene histograms overall, but could be implemented independent of the other changes. Basically the scale moves to be part of the x-axis of the colored-by gene. This would be best if #1035 were first implemented, since it would apply the scale to the bars as well, by design.

![Screen Shot 2020-02-25 at 8 41 30 AM](https://user-images.githubusercontent.com/53277128/75267181-bf136e80-57aa-11ea-87a3-0542ca51e429.png)

Figma of other formatting explorations:
https://www.figma.com/file/Cs4p5xuos4T4dXR87ftOuN/Reformat-histograms?node-id=64%3A0

**Comment by signechambers1** [comment] 2020-12-23 17:30
Closing as a low priority for 2021, if we get more feedback about this issue we will reconsider!

**Closed by signechambers1** 2020-12-23 17:30 UTC
Labels: P4
