### ISSUE TITLE
Support record-keeping for reproducibility

### ISSUE THREAD

**Issue by sidneymbell** [chanzuckerberg/cellxgene#97] opened 2018-06-21 18:48 UTC
This is usually the biggest downside to using GUIs for scientific data analysis. I think it's important to be able to share and reproduce:
  
* How the app was launched (what dataset, engine, methods, and parameters)  
* How the cells were subsetted (e.g., export cell IDs or criteria to csv or notebook)  
* Numerical results from diffexp  
* What values were selected for x, y, and color by  
* Visual results (e.g., export image)  

If we eventually enable interactive rerunning of analyses, these values should be logged for each computation (or at least every "exported" result). 

I.e., for any given analysis, I should be able to send results to collaborators. Given the input data file and analysis log or config file, they should be able to exactly reproduce those results.

**Comment by sidneymbell** [comment] 2018-06-21 19:04
Also under this umbrella are things like:
* For a given view, where did these values come from? (e.g., "What layout method was used? How were these clusters assigned? How was diffexp calculated? [all: with what parameters?] Where can I learn more about method X?")

* Wait, which cells were in set1 vs. set2? (redisplay selection)

**Comment by sidneymbell** [comment] 2019-02-07 19:08
As we've iterated on this, I think it would help facilitate the experimental <-> computational collaboration to have a log file that accompanies any exported results (annotations and/or diffexp results). This log file should be sufficient to reproduce the current view, meaning it needs to include:

1) what steps generated the current selection(s)
2) which selections were used for the diffexp results
3) settings used in cellxgene prepare (if applicable)

Ideally, this log file could also act as a config file to launch cellxgene to recreate the same view, given the same input data file.

**Comment by signechambers1** [comment] 2020-09-29 00:25
Closing as a duplicate of https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/cellxgene/658

**Closed by signechambers1** 2020-09-29 00:25 UTC
Labels: epic
