### ISSUE TITLE
support continuous coloring based on average expression of a set of genes

### ISSUE THREAD

**Issue by neuromusic** [chanzuckerberg/cellxgene#571] opened 2019-01-30 23:34 UTC
This use case was presented by @amaynard10's group.

They have multiple gene sets that are relevant to their analysis. For each gene set, they would like to see how the average expression of those genes varies across the set of cells in their analysis.

**Option 1**: Do this in scanpy (currently works)

*The user (data distributor) uses scanpy or seurat to perform this computation, selecting columns of the expression matrix and averaging them, then saving this as a new cell annotation (`.obs` in scanpy), which cellxgene then discovers.*

**Option 2: Do this in cellxgene**

*The user (data consumer) uses cellxgene to select a set of genes (through bulk add or through differential expression), then they are able to create a new annotation by averaging the expression levels of the set of genes.*

As we explore supporting workflows where the data consumer and data distributor are not the same person (that is, where we cannot assume that the cellxgene user is proficient in Seurat or scanpy), we may need to think seriously about Option 2.

**Comment by sidneymbell** [comment] 2019-07-22 18:49
This was requested by two different potential users at the ISMB poster session tonight :)

**Comment by signechambers1** [comment] 2021-04-19 17:23
Closing as a duplicate of https://app.zenhub.com/workspaces/cellxgene-explorer-600f112266e8830017f47e12/issues/chanzuckerberg/cellxgene/2036

**Closed by signechambers1** 2021-04-19 17:23 UTC
Labels: P3
