### ISSUE TITLE
Hard refresh clears user created labels without cell selections

### ISSUE THREAD

**Issue by colinmegill** [chanzuckerberg/cellxgene#998] opened 2019-10-29 19:01 UTC
To repro: 

0. Launch in anno mode
1. Create a category
2. Create a label, assign cells
2.1 Create a label, don't assign cells
3. Hard refresh
4. Category stays, label without cell assignment disappears

**Lifting up Bruce's implementation detail from comment:**

The core issue here is our data model, which currently has no way to persist unused labels. All labels are derived from their use in labeling cells - ie, at load time, labels are derived from the CSV file. If the label is not present in the file (ie, no cell annotated with that label), it is unknown.

Put another way, we derive the 'schema' from the data.

To save labels separate from data implies saving a schema - ie, for each category, a list of labels. We can do this, but I'm not sure how useful it is in practice - it would either be a custom header (comment) in the CSV, or a separate file entirely. And leaning hard toward keeping it simple, schema seems like extra complexity for not a lot of utility.

@sidneymbell, @liaprins-czi - I am curious about your thoughts on this, in particular the value of managing schema (label categories) separate from the data.

**Comment by bkmartinjr** [comment] 2019-11-05 00:42
The core issue here is our data model, which currently has no way to persist unused labels.  All labels are derived from their use in labeling cells - ie, at load time, labels are derived from the CSV file.  If the label is not present in the file (ie, no cell annotated with that label), it is unknown.

Put another way, we derive the 'schema' from the data.

To save labels separate from data implies saving a schema - ie, for each category, a list of labels.   We can do this, but I'm not sure how useful it is in practice - it would either be a custom header (comment) in the CSV, or a separate file entirely.   And leaning hard toward keeping it simple, schema seems like extra complexity for not a lot of utility.

@sidneymbell, @liaprins-czi - I am curious about your thoughts on this, in particular the value of managing schema (label categories) separate from the data.

**Comment by liaprins-czi** [comment] 2019-11-05 00:48
For me from UI perspective, it is unexpected behavior that a label is allowed to disappear, but since this is a lot of work for little value, then I think it's not important enough to do right now, relative to other work.

**Comment by sidneymbell** [comment] 2019-11-05 00:50
Agree with Lia!

**Comment by bkmartinjr** [comment] 2019-11-05 01:12
OK, I will remove from 0.13 but leave issue open.

I do think that in the fullness of time, we may have other reasons to manage a schema (eg, if we support non-string labels), so it will be good to retain this.

**Comment by bkmartinjr** [comment] 2020-07-18 15:52
Suggest deciding as part of user auth (M2) whether or not this is worth fixing, or is simply closed as is.

**Comment by tihuan** [comment] 2020-08-27 21:53
unless we hear from Ambrose, we won't need to work on this!

**Comment by signechambers1** [comment] 2020-09-29 23:11
Closing as low priority

**Closed by signechambers1** 2020-09-29 23:11 UTC
