### ISSUE TITLE
Diff exp suggestion: allow file output documenting resulting genes + their values per selection group

### ISSUE THREAD

**Issue by liaprins-czi** [chanzuckerberg/cellxgene#989] opened 2019-10-15 21:21 UTC
When talking with Bruce Aranow, he had a suggestion related to DE:
Allow export of DE results, e.g. as a CSV, wherein (prescriptively) rows = resulting gene names and column header = "group 1 selection" and "group 2 selection". The cells would be the values of expression for the genes per selection.

However, this may be less necessary if we have gene sets as a CSV that would function similarly to the annotations CSV. In that case, any time DE is run and produces a list of genes, they could auto-save to the `genesets.csv` (or whatever user calls it).

**Comment by alokito** [comment] 2019-11-01 19:57
When you say "values" do you mean the average value of that gene for all the cells in the selection?
Could we include two additional columns, "fold change" and "p-value" which include the fold change and p-value as are currently included with the histogram plots?

**Comment by liaprins-czi** [comment] 2019-11-01 21:20
Thanks for the clarification @alokito ! Yes I think the ask was for the avg, but would make sense to include the log fold change and p-value as well, if we end up doing this feature.

**Comment by signechambers1** [comment] 2020-10-21 16:56
Closing as a duplicate of https://github.com/chanzuckerberg/cellxgene/issues/1058

**Closed by signechambers1** 2020-10-21 16:56 UTC
Labels: P3
