### ISSUE TITLE
Add alpha to scatterplot

### ISSUE THREAD

**Issue by batson** [chanzuckerberg/cellxgene#657] opened 2019-03-20 20:57 UTC
Noise means I'll see a blob even when correlation is very high. Alpha would let me see what's going on in the bulk.

**Comment by bkmartinjr** [comment] 2019-03-20 21:29
Can you elaborate on what you mean by alpha, and how you want to control it?   I am guessing you want some sort of alpha channel (transparency) control, but I'm not clear on how that will help you see the bulk if all dots have the same alpha/transparency value.

**Comment by batson** [comment] 2019-03-21 01:18
I mean a slider for transparency.  It would let you see where dots are piled up. Basically the issue is that currently 100 dots on top of each other look the same as one dot on the same location.

![animerr](https://user-images.githubusercontent.com/1261162/54728643-56545880-4b3c-11e9-9802-a1651d0745bf.gif)

**Comment by batson** [comment] 2019-03-21 01:19
Seems related to #597

**Comment by signechambers1** [comment] 2020-09-29 21:57
Closing as a duplicate of #1457

**Closed by signechambers1** 2020-09-29 21:57 UTC
