### ISSUE TITLE
front-end handling of errors needs to improve

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#1338] opened 2020-04-02 14:26 UTC
The front-end does not cleanly report errors that occur during processing of the REST routes.  It should improve beyond the current (confusing) "HTTP error" red toast, as this may occur in a multi-dataset hosted environment

closely related to #1322

things we could do:
* retry on 504s or other things that look transient
* have upstream logic understand the error and cancel the operation (user can try later or try again)
* make the error friendlier (the scary HTTP error toast doesn't really help most users)

In case useful: https://reactjs.org/docs/error-boundaries.html

**Comment by liaprins-czi** [comment] 2020-04-14 16:50
@bkmartinjr Are these the only errors/types to be redesigned:
- HTTP errors
- bad data errors
- quota errors (eg, diffexp fails or times out)
or are there any others to take into account?

I'd like to see what they look like currently, so am wondering how to reproduce them? I think I can figure out how to reproduce the DE error if I use a huge dataset and select basically all the cells, it might trigger it. Is there are dataset file anyone has that will trigger the "bad data errors" so I can see what they look like? Is there a way to reproduce the HTTP errors?

**Comment by liaprins-czi** [comment] 2020-04-29 21:26
For posterity, here are what happens currently when I do each of the following:

**control + C in CLI in midst of lanch**
![control + C in CLI in midst of lanch](https://user-images.githubusercontent.com/53277128/80648395-f5789e80-8a24-11ea-81b9-5e158f5e7364.png)

**control + C in CLI then DE**
![control + C in CLI then DE](https://user-images.githubusercontent.com/53277128/80648410-fe697000-8a24-11ea-8bf9-ee1cf5037ffa.gif)

**control + C in CLI then search for a gene**
![control + C in CLI then search for a gene](https://user-images.githubusercontent.com/53277128/80648431-06291480-8a25-11ea-88a8-70c72d7fc161.gif)

**Comment by liaprins-czi** [comment] 2020-04-29 23:28
In general, if user can do anything to fix the situation causing the error, we should communicate what it is they can do. Since they have some control, at least to try troubleshooting, we should use orange toasts (rather than the more extreme red ones).

1.) (If possible) detect when the backend becomes disconnected (and maybe we wait until it has been disconnected for a certain length of time, e.g. a minute?), and communicate this in the front-end, instructionally telling the user what to do.

![1](https://user-images.githubusercontent.com/53277128/80656198-6e7ff200-8a35-11ea-8f67-7b163bc9b6a0.png)

- **Question:** Can we do this detecting of when the backend is connected or not? Would it be a big change to our current system? 
- **Question:** If we can do this feasibly, does it make sense to wait to message the user until the backend has been disconnected for a certain length of time, in case it just lost connection temporarily (or is that not how it works)? 
- **Question:** Would the user need to try re-launching cellxgene? Or is there anything else we could/should suggest for them to try in this scenario?
- **Question:** Is “server disconnected” accurate? Not sure what to say here...

2.) Assuming we do (1) above: the toasts are dismissible, so it is possible a user has dismissed the toast and then still tries to take an action that can’t be done when the backend is disconnected (e.g. retrieve a gene, run DE). Then we should issue a new toast, the same as before, explaining to relaunch cellxgene.
- We should show this ^^^ toast as soon as a user tries to do anything that will lead them to something not supported by the backend. For example, when they first make a selection and try to click to add it to one of the DE groups, rather than waiting until they’ve made both selections and then click the DE button (currently there is no message for DE). Or when user tries to add a gene, we should show the toast as soon as they click into the gene-add search bar, rather than waiting until they’ve input the gene and clicked the “Add gene” button (current behavior).
- Here is a mini prototype showing what this would be like for gene add:
https://www.figma.com/proto/HvHDmejndyZTymmB7VOkmk/1338-Error-handling?node-id=0%3A1&viewport=343%2C320%2C0.125&scaling=min-zoom
- We should not stack two of the same toasts. If user tries to take an action not supported when the backend is disconnected, and that original toast, (1) above, is still shown, we should not show another.
- _Alternatively, we could make the initial toast from (1 above) be not dismissible (I think this is an option in Blueprint), and then it stays there touting the current disconnected status, until user relaunches and is able to connect._

3.) For quota errors (e.g., DE fails or times out), we can tell the user that they can try again later or can try again with less total cells selected.

![2](https://user-images.githubusercontent.com/53277128/80656371-e6e6b300-8a35-11ea-81e5-97acbebc613b.png)

- **Question**: Would trying again later with that same amount of cells ever change the outcome, or would it always fail with a given number of cells?
- **Question:** Is there a way to know ahead of time if a quota type error ^^^ will fail, before letting it run for a long time? If so, we should communicate this as soon as possible rather than waiting (not sure if this type of error can be known ahead of time, though).

4.) “Bad data errors”... I’m not sure exactly what causes these; is it a corrupt or incorrect type of file? If there is something the user can do (like provide a different dataset file), then we should communicate this. If possible might be even better to communicate this in the CLI (in fact I think our CLI does have a message already if given the wrong filetype, at least). 
- **Question:** What causes a "bad data error"?
- **Question:** And what do they look like currently?

5.) If user cannot do anything 
@bkmartinjr you mentioned above about “retrying on 504s or other things that look transient”. In general I think it makes tons of sense to retry on things if it’s possible they’d work upon retrying. We could couple that approach with an error message if it ends up not working after a given amount of tries/time? 
- **Question:** What type of errors would these be? 
- **Question:** What would we want to/know enough about to communicate to the user about them?

https://blueprintjs.com/docs/#core/components/toast

**Comment by signechambers1** [comment] 2020-10-14 23:31
@colinmegill @maniarathi can you make a recommendation on priority here?

**Comment by maniarathi** [comment] 2020-10-15 04:30
This is low priority to me because it's specifically around handling the error message of hosted -- I'd consider prioritizing this once we have more users who are on hosted who might experience the unfriendly errors. I'd say P4, but open to suggestions @colinmegill.

**Comment by signechambers1** [comment] 2021-04-06 18:43
@maniarathi I'm going to close this for now, we can reopen if we want when we have more users on hosted.

**Closed by signechambers1** 2021-04-06 18:43 UTC
Labels: P4, dev-ish
