### ISSUE TITLE
diffexp timeout/504 on DEV cluster

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#1418] opened 2020-04-21 23:40 UTC
Test case:
1. Load Kidney Cell Atlas dataset
2. Select louvain label "6" and make that cell set 1
3. Select louvain label "7" and make that cell set 2
4. run diffexp and it times out (> 30 seconds) resulting in a 504 from load balancer

The total number of cells is ~24K, which is well under our configuration limit of 50K

**Comment by signechambers1** [comment] 2020-12-21 22:45
Closing as a duplicate of https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/cellxgene/1474

**Closed by signechambers1** 2020-12-21 22:45 UTC
