### ISSUE TITLE
Deep linking 

### ISSUE THREAD

**Issue by colinmegill** [chanzuckerberg/cellxgene#558] opened 2019-01-17 22:49 UTC
For ease of sharing, user should be able to share a url which replicates state on their box

cc & thank you @AMaynard10

**Comment by alokito** [comment] 2020-05-06 15:07
I got a request to support the ability to automatically color by specific gene/observation when cellxgene loads. This could be a command line argument or could be somehow embedded in the url (cellxgene/dataset/gene_name), so could be a subset of this deep linking request.

**Comment by signechambers1** [comment] 2020-09-29 01:57
Closing as a duplicate of [#658 ](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/cellxgene/658)

**Closed by signechambers1** 2020-09-29 01:57 UTC
Labels: enhancement

**Comment by heimannch** [comment] 2022-03-22 20:53
I contacted the team in the Slack channel, and it was recommended that I add my use case for deep linking.

Deep linking in the URL would also enable other data exploration platforms to provide their users with links to cellxgene with the settings that complement the visualizations provided in the first platform.
