### ISSUE TITLE
Main graph (cells) disappear

### ISSUE THREAD

**Issue by colinmegill** [chanzuckerberg/cellxgene#1325] opened 2020-04-01 14:44 UTC
With a large enough dataset and a small enough window size, deselection of cells causes them to disappear.

Probably due to a lack of min point size somewhere.

![image](https://user-images.githubusercontent.com/1770265/78150548-6f594000-7405-11ea-98fc-29e3d45816c3.png)

![image](https://user-images.githubusercontent.com/1770265/78150818-cc54f600-7405-11ea-8873-724ac3de57f1.png)

**Comment by liaprins-czi** [comment] 2020-06-22 18:22
My recommendation from design perspective would be to ensure that the unselected cells never get smaller than 1px. Then to keep them apart from the selected cells, the selected cells should never be smaller than 2px.

**Comment by bkmartinjr** [comment] 2020-07-16 16:28
@colinmegill - I am unable to reproduce, and the app currently behaves as @liaprins-czi suggests.  Can you provide a test case?

**Comment by signechambers1** [comment] 2020-10-01 01:09
Closing for now. @colinmegill if you can reproduce please reopen

**Closed by signechambers1** 2020-10-01 01:09 UTC
