### ISSUE TITLE
selecting two values of categorical metadata should allow display of p-value

### ISSUE THREAD

**Issue by alokito** [chanzuckerberg/cellxgene#1006] opened 2019-11-01 20:21 UTC
This is to assist users in determining the significance of the difference in expression in the mini-histograms from #827 . Currently it is hard to assess the significance of a difference between the histograms for two values of categorical metadata (i.e. two clusters) when a gene is selected.
Admittedly I don't know what a decent UI for this would look like.

**Comment by alokito** [comment] 2019-11-01 20:21
see also #1005

**Comment by colinmegill** [comment] 2019-11-25 19:28
cc @seve

**Comment by signechambers1** [comment] 2020-09-29 23:24
Closing as a duplicate of #915

**Closed by signechambers1** 2020-09-29 23:24 UTC
