### ISSUE TITLE
Simpler method to export incoming categories from .h5ad into the .csv for labels

### ISSUE THREAD

**Issue by liaprins-czi** [chanzuckerberg/cellxgene#986] opened 2019-10-15 20:57 UTC
Feedback from Bruce Aranow at CCHMC: wants to be able to take existing/initial categories that came in with the H5AD and export them (and their labels) in the CSV along with manually created labels.

Specific suggestion was to export only the categories selected (with their checkmarks on in the left sidebar) via an export button near the cxg logo in the top bar.

**Comment by signechambers1** [comment] 2020-09-29 23:06
Closing as a duplicate of https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell/28

**Closed by signechambers1** 2020-09-29 23:06 UTC
