### ISSUE TITLE
Enable comparisons between "set 1" and "everything not in set 1"

### ISSUE THREAD

**Issue by sidneymbell** [chanzuckerberg/cellxgene#99] opened 2018-06-21 19:06 UTC
E.g., How do B cells differ from all other cells in “world” (not just T cells / “Set 2”)?

**Comment by colinmegill** [comment] 2019-03-19 06:39
We could do this on the button itself. If two categories are selected for diffexp, we show the normal text:

![image](https://user-images.githubusercontent.com/1770265/54585339-2a2bc100-49f0-11e9-9c37-f5dc120b18b1.png)

If only one category is selected:

![image](https://user-images.githubusercontent.com/1770265/54585052-71fe1880-49ef-11e9-99e7-5481b8ca5137.png)

But nothing else, the button text changes to: 

![image](https://user-images.githubusercontent.com/1770265/54585270-00729a00-49f0-11e9-8fb1-302d158cb041.png)

And if world !== universe

![image](https://user-images.githubusercontent.com/1770265/54585311-1aac7800-49f0-11e9-815a-56e74f780adf.png)

**Comment by neuromusic** [comment] 2019-03-19 15:01
This could also be supported without any change to differential expression by enabling the user to invert their selection.

**Comment by colinmegill** [comment] 2019-03-19 17:06
We'll need that API for `currentSelection` either way - @bkmartinjr I imagine this is on the crossfilter as an API?

**Comment by bkmartinjr** [comment] 2019-03-19 18:04
Yes, it is quite simple to ask the crossfilter for the current selection.  We can add set operations (ie, all diff current-selection) as needed.   Lets talk when you need an API and we'll add it (the underlying set operations are already coded and in use by the crossfilter - just haven't exposed precisely the endpoint you need).

**Comment by sidneymbell** [comment] 2019-07-02 19:30
@colinmegill & @seve- How do you feel about adding an "inverse selection" button? This would help in the case of "I've made a complex selection that includes a lasso and I want to compare to everything else".

**Comment by colinmegill** [comment] 2019-08-05 18:05
Reference: 

https://github.com/HumanCellAtlas/matrix-service/blob/master/docs/HCA%20Matrix%20Service%20to%20Scanpy.ipynb

Thanks to @mckinsel

**Comment by colinmegill** [comment] 2019-08-05 18:44
This issue should be renamed `Enable comparisons between selected label, ie., `lung`,  and `everything not in selected label`

**Comment by signechambers1** [comment] 2020-09-29 00:32
Closing as duplicate of [#729](https://github.com/chanzuckerberg/cellxgene/issues/729)

**Closed by signechambers1** 2020-09-29 00:32 UTC
Labels: enhancement
