### ISSUE TITLE
Support python 3.9 in the desktop

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/cellxgene#2299] opened 2021-07-13 22:00 UTC
* [ ] Python 3.9 support
* [ ] Add to compatibility matrix in Github workflow

**Comment by MDunitz** [comment] 2021-07-20 17:58
Bruce has investigated and thinks this should be straightforward 
(if we bump up package dependencies to not support older versions of anndata)

**Comment by bkmartinjr** [comment] 2021-07-21 14:49
Partial fixes have been added to #2318

**Comment by maniarathi** [comment] 2021-09-14 17:30
Dupe of #2410.

**Closed by maniarathi** 2021-09-14 17:30 UTC
Labels: backend
