### ISSUE TITLE
bulk add genes input re-renders every time a histogram is added

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#1461] opened 2020-05-06 15:32 UTC
There is excessive re-rendering (visible in the UI) in the bulk add gene input field.   It appears to re-render every time a new continuous histogram is added, during data loading.

To recreate:
1. point browser at dataset with many, many continuous annotation dimensions (suggested: krasnow_lab_human_lung_cell_atlas_smartseq2-2.cxg)
2. early in the loading process, click on Bulk Add Genes so you see the input field with suggested gene names
3. as each histogram is incrementally added, you will see the input field re-render (each time suggesting a different set of random gene names)

**Comment by signechambers1** [comment] 2020-10-14 23:56
@colinmegill @maniarathi I can't reproduce this, Bulk Add loads last for me now. Please reply if you think we should keep this open, otherwise I will close.

**Comment by maniarathi** [comment] 2020-10-15 04:34
You're right @signechambers1 , I am unable to repro. Going ahead and closing.

**Closed by maniarathi** 2020-10-15 04:34 UTC
