### ISSUE TITLE
Shuffle the order in which points are plotted in the embedding browser

### ISSUE THREAD

**Issue by dburkhardt** [chanzuckerberg/cellxgene#1020] opened 2019-11-05 22:31 UTC
I've noticed some concerns about plotting density here, but I also wanted to add a suggestion to add an option to shuffle the order in which each point in the browser is plotted. 

This plot is unshuffled (i.e. plotting in the order of the array):
![image](https://user-images.githubusercontent.com/8322751/68251895-17ebab00-fff2-11e9-965b-535c93846c5b.png)

This plot is shuffled:

![image](https://user-images.githubusercontent.com/8322751/68251907-1fab4f80-fff2-11e9-91c1-ce4644ea6b0a.png)

If you're trying to gauge the density of each categorical label in the plot, shuffling the points first helps mitigate the issues with overplotting. I understand it is possible to shuffle prior to uploading the data, but I don't think most lay users would think to do this.

As an additional option, it might be helpful to give the option to change the order of sorting based on a given feature.

For example, we can look at the expression of a gene like Tbx6 on the shuffled plot:
![image](https://user-images.githubusercontent.com/8322751/68251829-f094de00-fff1-11e9-9f22-7e1aeb1e7c22.png)
But if you want to know where in the embedding that gene is expressed, sorting by expression of Tbx6 so that the highest-expressed genes are on top highlights where those cells are in the embedding.

![image](https://user-images.githubusercontent.com/8322751/68251870-0904f880-fff2-11e9-8c6d-13b486ea8b43.png)

As always, thanks for the excellent work

**Comment by colinmegill** [comment] 2019-11-05 23:05
@dburkhardt brilliant idea to sort cells given continuous values! Really like the idea.

**Comment by colinmegill** [comment] 2019-11-06 00:57
For other density related issues, see: #759, #817, #597, #657, #861

**Comment by dburkhardt** [comment] 2019-11-06 01:38
Glad you all like this! @colinmegill I would recommend against sorting points by continuous values by default because this can be misleading wrt the density of "positive" cells within a given space in the embedding. I think that it would be nice to make it an option "sort by value" or something whenever you select a new feature to color the plot by.

The way I think about this for continuous values is that sorting tells you "where" and shuffling tells you "how many"

**Comment by colinmegill** [comment] 2019-11-06 02:02
Roger. This perhaps implies a `sort by` dropdown next to the `choose layout` dropdown on the top bar, where options could include:

* default / unoptimized draw order
* shuffle / reshuffle

Or perhaps it's a `density management` dropdown as well, which would include additional concepts like: 

* alpha 
* binning

![image](https://user-images.githubusercontent.com/1770265/68261766-02788000-fff6-11e9-9e8b-44ba8019da57.png)

**Comment by dburkhardt** [comment] 2019-11-06 15:56
I think it's natural to have separate drop-downs / interaction elements for `plot by`, `color by`, `sort by` and `density management`

**Comment by colinmegill** [comment] 2019-11-06 16:10
Shuffle by default, other orderings by toggle?

**Comment by liaprins-czi** [comment] 2019-11-06 17:15
These are all great ideas to bring up, thanks @dburkhardt ! Also agree that shuffle by default is least misleading, but love the ability to sort by/layer by expression if color-by is applied to a gene.

**Comment by signechambers1** [comment] 2020-09-29 23:28
Closing as a duplicate of #1457

**Closed by signechambers1** 2020-09-29 23:28 UTC

**Comment by ShanSabri** [comment] 2021-03-05 20:29
It's unclear to me if this was resolved? Is there a way to sort continuous values?
