### ISSUE TITLE
[BUG] Feature x/y plot labels looks swapped

### ISSUE THREAD

**Issue by GHAStVHenry** [chanzuckerberg/cellxgene#1758] opened 2020-08-16 21:15 UTC
**Describe the bug**
Feature x/y plot axis label location makes it looks like they are represent the opposite axis

**To Reproduce**
1. choose first gene
2. choose second gene
3. select `plot x` and `plot y` for the 2 genes
4. look at scatter plot

**Expected behavior**
axis labels represent the correct axis

**Screenshots**
Below:
* CDH1 selected and displayed on x-axis
* EPCAM selected and displayed on y-axis
* **the axis label location makes it look like EPCAM is on the x-axis and CDH1 is on the y-axis**
![image](https://user-images.githubusercontent.com/38675268/90343984-42d04a00-dfdb-11ea-81b1-37fc4e3d1aca.png)

**Version (please complete the following information):**
 - Desktop or hosted?: hosted: cellxgene-gateway
 - Browser (if hosted) [e.g. chrome, safari]: chrome
 - Version [e.g. 0.13.0]: 0.16.0

**Additional context**

**Comment by maniarathi** [comment] 2020-08-17 00:24
Hi @GHAStVHenry , thanks for the bug report! We have PR #1754 in progress that will resolve this issue. If it's ok, we're going to go ahead and close this bug since it's a duplicate of #1749 which the PR is tagged to. We will update the community once we release 0.16.1 which will also contain this patch. Thank you again for the feedback!

**Closed by maniarathi** 2020-08-17 00:24 UTC
Labels: bug
