### ISSUE TITLE
coexpression heatmaps

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#1542] opened 2020-06-04 18:33 UTC
1. Users can create heatmap for:
   * geneset * geneset (coexpression)
   * geneset * category (which labels express which genes)
   * category * category (coexpression)
2. heatmap view (subset, pan/zoom) is sychronized with other views

includes heatmap/scatterplot component projects

**Comment by signechambers1** [comment] 2020-10-15 00:38
Closing as a duplicate of https://github.com/chanzuckerberg/cellxgene/issues/632

**Closed by signechambers1** 2020-10-15 00:38 UTC
