### ISSUE TITLE
move WSGI build artifact to docker

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#1514] opened 2020-06-04 00:34 UTC
We currently use the EB artifact.zip to package and deploy the WSGI package onto EB.  Move to a docker build artifact, allowing use with other platforms.

**Comment by signechambers1** [comment] 2020-10-15 00:03
Closing as a duplicate of https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/cellxgene/1866

**Closed by signechambers1** 2020-10-15 00:03 UTC
