### ISSUE TITLE
Enhance readability of cell labels when shown on the graph

### ISSUE THREAD

**Issue by jenzopr** [chanzuckerberg/cellxgene#1136] opened 2020-01-29 15:58 UTC
Hi!

When showing cell labels on the graph, they are sometimes hardly visible, like in the case of cluster numbers below.

<img width="700" alt="image" src="https://user-images.githubusercontent.com/8362850/73372433-7e156080-42b7-11ea-9d19-50c9e41465af.png">

Maybe visibility of those labels could be enhanced by placing them on a semi-transparent white box. I also thought of changing the color of the label, but this will certainly fail in other cases. 

Along the same line, I noticed that long cell labels are being truncated. Maybe they could be split into several lines instead?

The reason why I opened this issue is that my incentive (as a user, or bioinformatician) to use labels on the graph is mostly aesthetics. Therefore, I could easily live with a few cells being hidden by a larger box or similar, that keeps the label visible. 

Let me know what you think :-)
Jens

**Comment by colinmegill** [comment] 2020-01-29 16:09
cc @seve :)

**Comment by jenzopr** [comment] 2020-01-30 07:29
An alternative to the semi-transparent white box proposal from above may be to outline the individual characters/symbols from the label with a white border and maybe increase the font size a bit. I guess your UX team will figure what looks best 😉

**Comment by mweiden** [comment] 2020-01-31 16:44
@liaprins-czi let's sync on this. I'm interested in your take on the design.

**Comment by colinmegill** [comment] 2020-01-31 19:41
@mweiden this problem was solved in @seve's branch, but accidentally removed in a refactor, and the solution is slated to be put back in in the next release. Semi-transparent white overlay, uniformly applied to entire graph, when two states are met: 

1. `centroids are turned on`
2. `colorby is truthy`

**Comment by mweiden** [comment] 2020-01-31 21:14
@colinmegill so you and @seve are on it?

**Comment by bkmartinjr** [comment] 2020-01-31 22:51
possible duplicate of #1121?

**Comment by seve** [comment] 2020-02-03 18:57
@jenzopr Thank you for the actionable feedback on the labels overlay :)

As per #1121, I've planned to work on dropping the opacity of the graph as a whole when centroid labels are displayed.  As for label truncation, I'm planning on tweaking the truncation method to follow the left sidebar's middle truncation(see #911), but I'm now taking your idea of wrapping the label into consideration.

@liaprins-czi, I'd like to chat quickly about truncating vs. wrapping the labels on the graph.

**Closed** 2020-02-12 18:56 UTC
