### ISSUE TITLE
reembedding on hosted

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#1547] opened 2020-06-04 18:52 UTC
Allow user-driven reembedding of cell selections in hosted and desktop cellxgene. 
1. Use can request reembedding of current data, with choice of algo (umap, tsne, etc)
2. Optional dependencies computed as well (KNN, etc)

**Comment by colinmegill** [comment] 2020-06-09 15:08
Duplicate of https://github.com/chanzuckerberg/cellxgene/issues/280

**Comment by ambrosejcarr** [comment] 2020-08-05 12:31
I updated the issue to clarify that this is not a duplicate (this is intended to refer to the hosted version). However, linking to #280 is helpful, as that issue has the context. 

Linking a potential [umap performance speed up](https://arxiv.org/abs/2008.00325) based on nvidia rapids hardware/software h/t @colinmegill

**Comment by signechambers1** [comment] 2020-12-23 20:35
Closing as a low priority for 2021. Labeling with "reembedding" so we can find this issue in the future if needed.

**Closed by signechambers1** 2020-12-23 20:35 UTC
Labels: P4
